project:
  type: website
  output-dir: docs
execute: 
  freeze: auto
website:
  title: "current courses"
  navbar:
    right:
      - about.qmd
format:
  html:
    theme: theme.scss
    css: styles.css
format-links: [pdf]