project:
  type: website
  output-dir: docs

website:
  title: "current courses"
  navbar:
    right:
      - about.qmd
      
format:
  html:
    theme: theme.scss
    css: styles.css
format-links: [pdf]