project:
  output-dir: courses
format:
    html:
        theme: 
            - ../common/syll_styles.scss
        toc: false
        mainfont: IBM Plex Sans
    pdf:
        mainfont: IBM Plex Serif
        fontsize: 9pt
        linestretch: 1
        geometry:
            - left=0.75in
            - textwidth=5in
            - marginparwidth=1.5in
        toc: false
        number-sections: false
        include-in-header: ../common/syll_header.tex
        include-before-body: ../common/bef_body.tex
bibliography: ../common/big_bib.json
reference-section-title: Reading list
suppress-bibliography: false
csl: ../common/chicago-fullnote-bibliography-short-title-subsequent.csl




